### ISSUE TITLE
Similar gem focused only on Transactionally Staged Jobs

### ISSUE THREAD

**Issue by adamniedzielski** [fractaledmind/acidic_job#13]
Thank you for you work on this gem @fractaledmind 💛 Not knowing about this gem I created https://github.com/adamniedzielski/sidekiq-staged_push which focuses on Transactionally Staged Jobs as described in https://brandur.org/job-drain and Sidekiq specifically 😅 

It has a much more narrow scope and I managed to put it up in the Christmas break. I'll go through your code to compare the approaches. Feel free to close this issue.

**Comment by fractaledmind** [comment]
@adamniedzielski: I have just pushed the initial pre-releases of version 1.0.0. It was a large-scale reorganization and refactoring (as one does after one sprints into a problem space and starts somewhat randomly tackling problems) that tightens all of the screws but with no user-facing changes aside from the restructured database structure (moved from 2 tables to 1 and tweaked some attributes). 

I think the code is now better organized and thus hopefully easier to follow. I have read thru your gem and you accomplish the task in a notably different way. I would love to have you experiment with my approach and then have us chat about the pros and cons for each approach. Ideally, I would like to have the most robust setup for transactionally-staged jobs that I can, so if your approach is better, I would love to shift over (if we can also keep all of the other features intact). Anyway, would love to chat more about it soon.

**Comment by adamniedzielski** [comment]
I read through some of the changes. I don't think I have much to contribute to the conversation at this point. I don't use my own gem in any production application. Maybe after some people start using it in production they will be opening issues and I see. Right now I don't have the need to convince anybody to anything 😉
